### ISSUE TITLE
installing problem 

### ISSUE THREAD

**Issue by strRang** [chenglongfu11/icepy#1]
Hi. 

I have a very simple question. 
I'm struggling with this error, Could not find a version that satisfies the requirement csv <from icepy> <from versions: none> 
Is any specific version of python needed? 

please help!

**Comment by chenglongfu11** [comment]
Hi,

Nice to hear from you! It is my pleasure to notice the package is used by someone.
I feel appreciated that you reported this issue. It was a mistake since 'csv' should be the default package in Python. It is now solved with a new version 0.0.7. Please be aware you are using 32-bit Python if you are using 32-bit API !

Feel free to inform me if any questions!
Best regards,
Clong

**Comment by strRang** [comment]
Thank you for your quick respond!

While I followed the Tutorial1's code, `result, new_file = idm.zoneclone(floor_ht, num_floors)`
I got this error, ArgumentError: argument 1: <class 'TypeError'>: wrong type

The reason I found this library is to compare the hourly performance(Load and daylight illuminance) of external movable shading device.
But I can't find any codes about modelling(calculating) of shading or importing vector graphic files(in my case, I have every shape of external shading device's model in SketchUp).

Is it possible to import SketchUp file?
If it is not, I can make idm files which have manually imported shadings. 

>>But is it possible to adjust simulation duration in this library?? (e.g. from certain day's 12:00 to 13:00)<< This is the real problem to me. 

I'll appreciate if you answer me : )

**Comment by chenglongfu11** [comment]
Thanks for your information!
I didn't meet the error that you mentioned. Did you use the building model from the Building folder? However, I will do another check.

Regarding your requirements in the modeling of shading, I am sorry to say the current version of icepy is still under development. It supports only the modification of building envelopment components. It doesn't support either modeling of shading or importing SketchUp file. However, your suggestion values! We will add them to the plan!

**Comment by strRang** [comment]
Ahh ok then! 

is it available to adjust running period of simulation??

**Comment by kristss** [comment]
Did you find a solution? I seem to get the same error while running `result, new_file = idm.zoneclone(floor_ht, num_floors)` . 

Will post a reply if resolve it.

The full traceback is:
```
<ipython-input-8-a0a087ec30a0> in <module>
----> 1 result, new_file = idm.zoneclone(floor_ht, num_floors)
      2 new_file

C:\ProgramData\Anaconda3\lib\site-packages\icepy\modeleditor.py in zoneclone(self, floor_ht, num_floors)
     71   def zoneclone(self, floor_ht, num_floors):
     72 
---> 73       result, new_name = self.zoneClone.clone_zone(self.building, floor_ht, num_floors)
     74 
     75       new_path = self.folder + new_name + '.idm'

C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in clone_zone(self, building, ceiling_ht, num_floor)
     50         :return:
     51         """
---> 52         zones = call_ida_api_function(ida_lib.getChildrenOfType, building, b"ZONE")
     53         results = []
     54 

C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in call_ida_api_function(fun, *args)
    136   p = ctypes.create_string_buffer(5000)
    137   args = args + (p,len(p))
--> 138   res = fun(*args)
    139   if res == 0:
    140     return ida_poll_results_queue(0.1)

ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**Comment by chenglongfu11** [comment]
> Did you find a solution? I seem to get a similar error while running `result, new_file = idm.zoneclone(floor_ht, num_floors)` .
> 
> Will post a reply if resolve it.
> 
> The full traceback is:
> 
> ```
> Changing ceiling height
> 4
> 2.6
> ---------------------------------------------------------------------------
> ArgumentError                             Traceback (most recent call last)
> <ipython-input-47-5eb27cb825ca> in <module>
> ----> 1 result, new_file = idm.zoneclone(floor_ht, num_floors)
>       2 result
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\modeleditor.py in zoneclone(self, floor_ht, num_floors)
>      71   def zoneclone(self, floor_ht, num_floors):
>      72 
> ---> 73       result, new_name = self.zoneClone.clone_zone(self.building, floor_ht, num_floors)
>      74 
>      75       new_path = self.folder + new_name + '.idm'
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in clone_zone(self, building, ceiling_ht, num_floor)
>      57 
>      58             val = zones[0]
> ---> 59             if self.edit_ceiling_ht(val, ceiling_ht):  # Edit the ceiling ht of the base zone
>      60                 for j in range(num_floor - 1):
>      61                     zone_name = "Zone " + str(j + 2)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in edit_ceiling_ht(self, val, ceiling_ht)
>      28 
>      29         text_to_send = "{\"type\":\"number\",\"value\":" + "{0:.1f}".format(ceiling_ht) + "}"  # float(ceiling_ht)
> ---> 30         res_1 = call_ida_api_function(ida_lib.setAttribute, b"VALUE", ceiling, text_to_send.encode())
>      31 
>      32         # Check the current ceiling height
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in call_ida_api_function(fun, *args)
>     136   p = ctypes.create_string_buffer(5000)
>     137   args = args + (p,len(p))
> --> 138   res = fun(*args)
>     139   if res == 0:
>     140     return ida_poll_results_queue(0.1)
> 
> ArgumentError: argument 2: <class 'TypeError'>: wrong type
> ```

**Comment by chenglongfu11** [comment]
Hi kristss,

It is nice to see that you are interested in this repository.

I haven't checked it for a period. Therefore, I am afraid I could not check the issue you met recently. 
Reading from your message, I think the error was caused because of the format of the value of the ceiling height. If the value '2.6' is not feasible, what if you try '3' ? 
To be honest, the API library of IDA ICE is sometimes problematic.

Regards,

**Comment by kristss** [comment]
Hi, thanks for getting back to me so quickly. 

I'm getting two variations of this argument error, I think they were either caused by the MessageBrokerService not running or that I had replaced the idaapi2.dll in the bin folder by mistake. I did a reinstall of IDA, and put the idaapi2.dll (from the 64 bit API folder), libzmq-v100-mt-4_0_4.dll and libzmq-mt-4_3_1.dll into a separate folder on my drive. I also replaced the util.py file in ...\site-packages\icepy with the one in the 64 bit API folder, linking `path_to_lib` in def start() to the folder with the dlls, but now I'm facing a different error at the same step. 

So far, following the steps in tutorial 1, the IDA interface opens and loads the model, e.g. ut1.idm, but when I get to `result, new_file = idm.zoneclone(floor_ht, num_floors)`, Then there is this OS error, or sometimes the previous error. I may try the 32-bit version of Python and dll's next.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-35-5eb27cb825ca> in <module>
----> 1 result, new_file = idm.zoneclone(floor_ht, num_floors)
      2 result

C:\ProgramData\Anaconda3\lib\site-packages\icepy\modeleditor.py in zoneclone(self, floor_ht, num_floors)
     71   def zoneclone(self, floor_ht, num_floors):
     72 
---> 73       result, new_name = self.zoneClone.clone_zone(self.building, floor_ht, num_floors)
     74 
     75       new_path = self.folder + new_name + '.idm'

C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in clone_zone(self, building, ceiling_ht, num_floor)
     50         :return:
     51         """
---> 52         zones = call_ida_api_function(ida_lib.getChildrenOfType, building, b"ZONE")
     53         results = []
     54 

C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in call_ida_api_function(fun, *args)
    140   res = fun(*args)
    141   if res == 0:
--> 142     return ida_poll_results_queue(0.1)
    143   elif res > 0 :
    144     p = ctypes.create_string_buffer(res)

C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in ida_poll_results_queue(time_interval)
    126   while poll_result == False:
    127     time.sleep(time_interval)
--> 128     poll_res = ida_lib.pollForQueuedResults(doc_str, len(doc_str))
    129     poll_result2 = json.loads(doc_str.value.decode("utf-8"))
    130     if isinstance(poll_result2, list):

OSError: [WinError -529697949] Windows Error 0xe06d7363
```

**Comment by xavfa** [comment]
> Hi, thanks for getting back to me so quickly.
> 
> I'm getting two variations of this argument error, I think they were either caused by the MessageBrokerService not running or that I had replaced the idaapi2.dll in the bin folder by mistake. I did a reinstall of IDA, and put the idaapi2.dll (from the 64 bit API folder), libzmq-v100-mt-4_0_4.dll and libzmq-mt-4_3_1.dll into a separate folder on my drive. I also replaced the util.py file in ...\site-packages\icepy with the one in the 64 bit API folder, linking `path_to_lib` in def start() to the folder with the dlls, but now I'm facing a different error at the same step.
> 
> So far, following the steps in tutorial 1, the IDA interface opens and loads the model, e.g. ut1.idm, but when I get to `result, new_file = idm.zoneclone(floor_ht, num_floors)`, Then there is this OS error, or sometimes the previous error. I may try the 32-bit version of Python and dll's next.
> 
> ```
> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-35-5eb27cb825ca> in <module>
> ----> 1 result, new_file = idm.zoneclone(floor_ht, num_floors)
>       2 result
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\modeleditor.py in zoneclone(self, floor_ht, num_floors)
>      71   def zoneclone(self, floor_ht, num_floors):
>      72 
> ---> 73       result, new_name = self.zoneClone.clone_zone(self.building, floor_ht, num_floors)
>      74 
>      75       new_path = self.folder + new_name + '.idm'
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in clone_zone(self, building, ceiling_ht, num_floor)
>      50         :return:
>      51         """
> ---> 52         zones = call_ida_api_function(ida_lib.getChildrenOfType, building, b"ZONE")
>      53         results = []
>      54 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in call_ida_api_function(fun, *args)
>     140   res = fun(*args)
>     141   if res == 0:
> --> 142     return ida_poll_results_queue(0.1)
>     143   elif res > 0 :
>     144     p = ctypes.create_string_buffer(res)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in ida_poll_results_queue(time_interval)
>     126   while poll_result == False:
>     127     time.sleep(time_interval)
> --> 128     poll_res = ida_lib.pollForQueuedResults(doc_str, len(doc_str))
>     129     poll_result2 = json.loads(doc_str.value.decode("utf-8"))
>     130     if isinstance(poll_result2, list):
> 
> OSError: [WinError -529697949] Windows Error 0xe06d7363
> ```

**Comment by xavfa** [comment]
Hi, I am also trying to use this API option with IDA and thanks to Icepy a part of the job seem to be done. I encountered the same issues as above for the 32bit version of phyton...
I have tried with no succes the 64bit version from now (python 3,7, with virtualenv) due to dll issues still seen as 32bit version... I will try continue my digging activity on this. So I installed a 32bit pyhton 3.7. hten I encountered the same issue of OSError: [WinError -529697949] Windows Error 0xe06d7363. Some errors (maybe due to my python version (?) are that the too much argument are given from function's output.
def showSingleChild(parent, child_name): should return only 'element'
in def edit_ceiling_ht, I just gave ceiling [0] to setAttribut function and it works,
same issue for the saving step. the idm.zoneclone(floor_ht, num_floors) return two element and only the path is needed

hope this will help you.
bests,

**Comment by xavfa** [comment]
Oh, some last element that are still weird to me : I had some identation issues from the modeleditor (editor version (?) and I have a folder icepy2 in scripts-package as well after having made pip install icepy. Why is there this extra folder ? I have made my changes in the icepy folder, keeping icepy2 folder as it was.

**Comment by chenglongfu11** [comment]
> Oh, some last element that are still weird to me : I had some identation issues from the modeleditor (editor version (?) and I have a folder icepy2 in scripts-package as well after having made pip install icepy. Why is there this extra folder ? I have made my changes in the icepy folder, keeping icepy2 folder as it was.

Hi xavfa,
I am sorry that I could not follow this project properly since I have other jobs to do. 
The modeleditor.py is the aggregation of most of the useful functions developed in icepy. The idea to do so is to avoid users being lost in the sea of .py files.
I am not sure what 'icepy2' is, to be honest. From the developer side, there's no such folder existing when I upload the pipy package. 
If you find the difficulty in understanding the pip install, I would recommend you to download this repository and use these python files directly. However, you need to change the way to 'import' accordingly. 
Best regards

**Comment by yacinetayeb** [comment]
> Did you find a solution? I seem to get a similar error while running `result, new_file = idm.zoneclone(floor_ht, num_floors)` .
> 
> Will post a reply if resolve it.
> 
> The full traceback is:
> 
> ```
> Changing ceiling height
> 4
> 2.6
> ---------------------------------------------------------------------------
> ArgumentError                             Traceback (most recent call last)
> <ipython-input-47-5eb27cb825ca> in <module>
> ----> 1 result, new_file = idm.zoneclone(floor_ht, num_floors)
>       2 result
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\modeleditor.py in zoneclone(self, floor_ht, num_floors)
>      71   def zoneclone(self, floor_ht, num_floors):
>      72 
> ---> 73       result, new_name = self.zoneClone.clone_zone(self.building, floor_ht, num_floors)
>      74 
>      75       new_path = self.folder + new_name + '.idm'
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in clone_zone(self, building, ceiling_ht, num_floor)
>      57 
>      58             val = zones[0]
> ---> 59             if self.edit_ceiling_ht(val, ceiling_ht):  # Edit the ceiling ht of the base zone
>      60                 for j in range(num_floor - 1):
>      61                     zone_name = "Zone " + str(j + 2)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\zoneclone.py in edit_ceiling_ht(self, val, ceiling_ht)
>      28 
>      29         text_to_send = "{\"type\":\"number\",\"value\":" + "{0:.1f}".format(ceiling_ht) + "}"  # float(ceiling_ht)
> ---> 30         res_1 = call_ida_api_function(ida_lib.setAttribute, b"VALUE", ceiling, text_to_send.encode())
>      31 
>      32         # Check the current ceiling height
> 
> C:\ProgramData\Anaconda3\lib\site-packages\icepy\util.py in call_ida_api_function(fun, *args)
>     136   p = ctypes.create_string_buffer(5000)
>     137   args = args + (p,len(p))
> --> 138   res = fun(*args)
>     139   if res == 0:
>     140     return ida_poll_results_queue(0.1)
> 
> ArgumentError: argument 2: <class 'TypeError'>: wrong type
> ```

 I seem to get the same error while running the same line.
The IDAMessageBrokerService actually doesnt work for me. I tried uninstalling ida und reinstalling it, nothing changed. I always get the error 
"cant start the ' IDAMessageBrokerService' in 'local computer'
The Service did not Respond to the Start or Control Request in a Timely Fashion"
anyone have any idea how to solve it?
